---
- name: Update credentials
  ansible.builtin.set_fact:
    ansible_user: '{{ domain_admin_user }}'
    ansible_become_user: '{{ domain_admin_user }}'
    ansible_password: '{{ domain_admin_password }}'

- name: Reset connection
  ansible.builtin.meta: reset_connection
